var sampleData = {  
   "attendance":[  
      {  
         "eventNo":"2075",
         "name":"Convocation 2017",
         "date":1503253800,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":100,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2170",
         "name":"Convocation Part II",
         "date":1503284400,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":80,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2058",
         "name":"Choir Kick-Off",
         "date":1503347400,
         "type":"rehearsal",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":70,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2059",
         "name":"Rehearsal 08-28",
         "date":1503957600,
         "type":"rehearsal",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":60,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2041",
         "name":"Founders' Council Brunch Reception",
         "date":1504967400,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":50,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2166",
         "name":"Engagement Fair Tabling!",
         "date":1505487600,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":40,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2132",
         "name":"Retreat!",
         "date":1505505600,
         "type":"tutti",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-35,
         "partialScore":5,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2062",
         "name":"Rehearsal 09-18",
         "date":1505772000,
         "type":"rehearsal",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":-5,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2169",
         "name":"Vigil Flash Mob",
         "date":1505779200,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":-15,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2167",
         "name":"Army ROTC Promotion Ceremony",
         "date":1506091500,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":-25,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2172",
         "name":"Beach Bois Gig",
         "date":1506204000,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":-35,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2063",
         "name":"Rehearsal 09-25",
         "date":1506376800,
         "type":"rehearsal",
         "shouldAttend":true,
         "didAttend":true,
         "late":0,
         "pointChange":0,
         "partialScore":-35,
         "explanation":"No point change for attending required event"
      },
      {  
         "eventNo":"2165",
         "name":"September Forum",
         "date":1506384000,
         "type":"ombuds",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":0,
         "partialScore":-35,
         "explanation":"Did not attend and not expected to"
      },
      {  
         "eventNo":"2173",
         "name":"Flash Mob Part 1: The Phantom Menace",
         "date":1506610800,
         "type":"volunteer",
         "shouldAttend":false,
         "didAttend":false,
         "late":0,
         "pointChange":0,
         "partialScore":-35,
         "explanation":"Did not attend and not expected to"
      },
      {  
         "eventNo":"2048",
         "name":"Rehearsal 10-02",
         "date":1506981600,
         "type":"rehearsal",
         "shouldAttend":true,
         "didAttend":true,
         "late":0,
         "pointChange":0,
         "partialScore":35,
         "explanation":"No point change for attending required event"
      },
      {  
         "eventNo":"2168",
         "name":"October Forum",
         "date":1506988800,
         "type":"ombuds",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":0,
         "partialScore":35,
         "explanation":"Did not attend and not expected to"
      },
      {  
         "eventNo":"2171",
         "name":"Fall Break Fundatory",
         "date":1507330800,
         "type":"ombuds",
         "shouldAttend":false,
         "didAttend":false,
         "late":0,
         "pointChange":0,
         "partialScore":-35,
         "explanation":"Did not attend and not expected to"
      },
      {  
         "eventNo":"2050",
         "name":"Rehearsal 10-16",
         "date":1508191200,
         "type":"rehearsal",
         "shouldAttend":true,
         "didAttend":true,
         "late":0,
         "pointChange":0,
         "partialScore":75,
         "explanation":"No point change for attending required event"
      },
      {  
         "eventNo":"2074",
         "name":"Naming Ceremony for Krone Engineered Biosystems bu",
         "date":1508589000,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":-45,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2175",
         "name":"Old Gold Reunion",
         "date":1508594400,
         "type":"tutti",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-35,
         "partialScore":-80,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2177",
         "name":"HOCO Flash Mob UNO",
         "date":1508612400,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":-90,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2133",
         "name":"Homecoming Sound Check",
         "date":1508621400,
         "type":"tutti",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-35,
         "partialScore":-125,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2176",
         "name":"Homecoming Alma Mater!",
         "date":1508626800,
         "type":"tutti",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-35,
         "partialScore":-160,
         "explanation":"Full deduction for unexcused absence from event"
      },
      {  
         "eventNo":"2051",
         "name":"Rehearsal 10-23",
         "date":1508796000,
         "type":"rehearsal",
         "shouldAttend":true,
         "didAttend":true,
         "late":0,
         "pointChange":0,
         "partialScore":100,
         "explanation":"No point change for attending required event"
      },
      {  
         "eventNo":"2179",
         "name":"Family Weekend Flash Mob",
         "date":1509204600,
         "type":"volunteer",
         "shouldAttend":true,
         "didAttend":false,
         "late":0,
         "pointChange":-10,
         "partialScore":0,
         "explanation":"Full deduction for unexcused absence from event"
      }
   ],
   "final_score":0,
   "status":"ok"
};